### ISSUE TITLE
getNumericValue is null when locale is fa-IR

### ISSUE THREAD

**Issue by moeindev** [CottaCush/CurrencyEditText#5] opened 2019-11-30 14:47 UTC

**Comment by Aiuspaktyn** [comment] 2019-12-07 17:35
Same problem when the locale is italian, the problem is when there is the "," instead of "." for decimal...

a fast fix:

```
fun getNumericValue(): Double? {
        val tempParse = parseMoneyValue(text.toString(), textWatcher.decimalFormatSymbols.groupingSeparator.toString(), currencySymbolPrefix)
        return tempParse.toDoubleOrNull() ?: tempParse.replace(",", ".").toDoubleOrNull()
    }
```

**Comment by rasheedsulayman** [comment] 2019-12-08 16:25
Nice suggestion @Aiuspaktyn. 
The issue can also be fixed by formatting output values from the `EditText` with a `NumberFormatter` created with the user supplied locale. The fix is in #6

**Closed as completed** 2019-12-09 15:02 UTC
Labels: bug
